// Shared simulation data used by all homepage designs
export const simulations = [
    {
        id: 'atomic-structure',
        title: 'Atom Simulator',
        description: 'Visualize atomic structure with Bohr model and electron probability clouds. Build and explore compounds.',
        icon: '⚛️',
        iconBg: 'rgba(59, 130, 246, 0.15)',
        status: 'available',
        path: '/atom-simulator',
        category: 'Quantum',
    },
    {
        id: 'electromagnetic-fields',
        title: 'Electromagnetic Fields',
        description: 'Visualize electric and magnetic field lines in complex setups.',
        icon: '⚡',
        iconBg: 'rgba(6, 182, 212, 0.15)',
        status: 'available',
        path: '/electromagnetic',
        category: 'Classical',
    },
    {
        id: 'double-pendulum',
        title: 'Double Pendulum',
        description: 'Explore the classic chaotic system. Trace paths, analyze phase space, and observe the butterfly effect.',
        icon: '⚖️',
        iconBg: 'rgba(234, 179, 8, 0.15)',
        status: 'available',
        path: '/double-pendulum',
        category: 'Chaos',
    },
    {
        id: 'fluid-dynamics',
        title: 'Fluid Dynamics',
        description: 'Next-gen fluid simulation using WebGPU Compute Shaders. Interactive water surface with real-time wave propagation.',
        icon: '🌊',
        iconBg: 'rgba(124, 58, 237, 0.15)',
        status: 'available',
        path: '/fluid-dynamics',
        category: 'Classical',
    },
    {
        id: 'wave-interference',
        title: 'Wave Interference',
        description: 'Interactive ripple tank. Experiment with diffraction, refraction, and interference patterns.',
        icon: '🌊',
        iconBg: 'rgba(139, 92, 246, 0.15)',
        status: 'available',
        path: '/wave-interference',
        category: 'Waves',
    },
    {
        id: 'soft-body',
        title: 'Soft Body Simulation',
        description: 'Deformable physics engine. Play with cloth, jellies, and elastic collisions.',
        icon: '🧶',
        iconBg: 'rgba(236, 72, 153, 0.15)',
        status: 'available',
        path: '/soft-body',
        category: 'Classical',
    },
    {
        id: 'general-relativity',
        title: 'General Relativity',
        description: 'Spacetime curvature simulator. Black holes, gravitational lensing, and geodesics in dual WebGL/WebGPU modes.',
        icon: '🌌',
        iconBg: 'rgba(168, 85, 247, 0.15)',
        status: 'available',
        path: '/general-relativity',
        category: 'Relativity',
    },
    {
        id: 'quantum-sandbox',
        title: 'Quantum Wave Sandbox',
        description: 'Visualize quantum tunneling and interference with the Schrödinger equation using WebGPU compute shaders.',
        icon: '🔬',
        iconBg: 'rgba(147, 51, 234, 0.15)',
        status: 'available',
        path: '/quantum-sandbox',
        category: 'Quantum',
    },
    {
        id: 'aerodynamics',
        title: 'Virtual Wind Tunnel',
        description: 'Lattice Boltzmann CFD sandbox. Draw obstacles and visualize turbulence, vorticity, drag and lift in real-time.',
        icon: '💨',
        iconBg: 'rgba(56, 189, 248, 0.15)',
        status: 'available',
        path: '/aerodynamics',
        category: 'Classical',
    },
    {
        id: 'thermodynamics',
        title: 'Entropy Lab',
        description: '20,000 particle hard-sphere simulation using WebGPU. Experiment with Ideal Gas Law, Adiabatic processes, and Maxwell\'s Demon.',
        icon: '🔥',
        iconBg: 'rgba(249, 115, 22, 0.15)',
        status: 'available',
        path: '/thermodynamics',
        category: 'Thermodynamics',
    },
    {
        id: 'electronics',
        title: 'Electronics & Circuits',
        description: 'Interactive circuit simulator with AC phasors, diode waveform shaping, and network theorem sandbox.',
        icon: '🔌',
        iconBg: 'rgba(16, 185, 129, 0.15)',
        status: 'available',
        path: '/electronics',
        category: 'Classical',
    },
];

export const threeBodySim = {
    id: 'three-body',
    title: 'Three-Body Problem',
    description: 'Explore the chaotic dance of three celestial bodies under gravitational influence. Modify mass, velocity, and observe the butterfly effect in real-time.',
    icon: '🪐',
    iconBg: 'rgba(99, 102, 241, 0.15)',
    status: 'available',
    path: '/three-body',
    category: 'Chaos',
    tags: ['Gravity', 'Chaos Theory', 'Orbital Mechanics'],
};

export const categories = ['All', 'Quantum', 'Classical', 'Chaos', 'Waves', 'Relativity', 'Thermodynamics'];
